# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
