version: '2'
services:
   db:
     image: postgres

   redis:
     restart: always
     image: redis:latest
     expose:
       - "6379"

   web:
     build: .
     command: bash -c "./manage.py migrate; while :; do ./manage.py runserver 0.0.0.0:8000; sleep 1; celery worker -A restaurant -l info; done; "
     volumes:
       - .:/src
     ports:
       - "8000:8000"
     depends_on:
       - db

