# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20170517_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='catalogue.Product')),
            ],
        ),
    ]
