# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0004_extraimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.TimeStampedModel')),
                ('rating', models.PositiveSmallIntegerField()),
                ('rated_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalogue.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('catalogue.timestampedmodel',),
        ),
    ]
