# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0008_auto_20170523_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.TimeStampedModel')),
                ('feedback', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Invalid'), (3, 'Completed')], default=0)),
                ('answer', models.TextField()),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answers', to=settings.AUTH_USER_MODEL)),
                ('feedback_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='catalogue.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('catalogue.timestampedmodel',),
        ),
    ]
