# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0009_productfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionLetter',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogue.TimeStampedModel')),
                ('promo_subject', models.CharField(max_length=120)),
                ('promo_text', models.TextField()),
                ('start_at', models.DateTimeField()),
            ],
            bases=('catalogue.timestampedmodel',),
        ),
    ]
