# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20170519_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='fixed_shipping_price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='shipping_price_per_km',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
    ]
