# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0005_siteconfig_free_shipping_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email to send notification about some problems with website'),
        ),
    ]
