# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
