# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
